# Generated by Django 6.0.4 on 2026-04-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchAnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('linked_patients', models.IntegerField(default=0)),
                ('unlinked_rows', models.IntegerField(default=0)),
                ('etl_report', models.JSONField(default=dict)),
                ('ml_results', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
