# Generated by Django 6.0.4 on 2026-04-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_batchanalysisreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
