# Generated by Django 6.0.4 on 2026-05-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_batchanalysisreport_owner_patient_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='weight',
            new_name='bmi',
        ),
    ]
