# Generated by Django 6.0.4 on 2026-06-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='model_type',
            field=models.CharField(choices=[('linear_regression', 'Linear Regression'), ('kmeans', 'KMeans Clustering'), ('logistic', 'Logistic Regression'), ('decision_tree', 'Decision Tree'), ('rule_based', 'Rule Based'), ('isolation_forest', 'Isolation Forest')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='analysisresult',
            unique_together={('patient', 'model_type')},
        ),
    ]
